# Generated by Django 2.1.1 on 2018-11-06 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20181022_1918'),
        ('products', '0011_auto_20181102_1553'),
    ]

    operations = [
    ]
